const MenuD = [
    {
        id: 1,
        image: "./images/WMSandB.png",
        alt: "T-Sandwich",
        name: 'T-Sandwich',
        category: 'breakfast',
        price: 9,
    },
    {
        id: 2,
        image: "images/TAvoB.png",
        alt: "Avocado sandwich",
        name: 'Avocado sandwich',
        category: 'breakfast',
        price: 11,
    },
    {
        id: 3,
        image: "images/WSwaffleB.png",
        alt: "Waffles",
        name: 'Waffles',
        category: 'breakfast',
        price: 12,
    },
    {
        id: 4,
        image: "./images/eggSandB.png",
        alt: "Egg and meat",
        name: "Egg and meat",
        category: "breakfast",
        price: 12,
    },
    {
        id: 5,
        image: "./images/KabsaL.png",
        alt: "Kabsa",
        name: "Kabsa",
        category: "lunch",
        price: 22,
    },
    {
        id: 6,
        image: "./images/TheChiSL.png",
        alt: "Chicken with potato",
        name: "Chicken with potato",
        category: "lunch",
        price: 21,
    },
    {
        id: 7,
        image: "./images/ChickenLegsL.png",
        alt: "Chicken legs",
        name: "Chicken wings",
        category: "lunch",
        price: 25,
    },
    {
        id: 8,
        image: "./images/Burger1.png",
        alt: "Big burger",
        name: "Mega burger",
        category: "evening",
        price: 33,
    },
    {
        id: 9,
        image: "./images/Burger2.png",
        alt: "Burger",
        name: "Eiffel Burger",
        category: "evening",
        price: 18,
    },
    {
        id: 10,
        image: "./images/AvoRemo.png",
        alt: "Avocado with eggs",
        name: "Avocado with eggs",
        category: "evening",
        price: 18,
    },
    {
        id: 11,
        image: "./images/PotatoE.png",
        alt: "Potatoes",
        name: "Potatoes",
        category: "evening",
        price: 16,
    },
    {
        id: 12,
        image: "./images/SaladNE.png",
        alt: "Nuts salad",
        name: "Nuts salad",
        category: "evening",
        price: 14,
    },
    {
        id: 13,
        image: "./images/SalamonD.png",
        alt: "Salmon salad",
        name: "Salmon salad",
        category: "dinner",
        price: 35,
    },
    {
        id: 14,
        image: "./images/ShawarmaD.png",
        alt: "Shawarma",
        name: "Shawarma",
        category: "dinner",
        price: 10,
    },
    {
        id: 15,
        image: "./images/RishSaladD.png",
        alt: "Rish salad",
        name: "Rish salad",
        category: "dinner",
        price: 40,
    },
]

export default MenuD