const MenuD = [
    {
        id: 1,
        fav: "./images/Favorite.png",
        image: "./images/WMSandB.png",
        alt: "T-Sandwich",
        name: 'T-Sandwich',
        category: 'breakfast',
        price: '9$',
        amount: 0,
    },
    {
        id: 2,
        fav: "./images/Favorite.png",
        image: "images/TAvoB.png",
        alt: "Avocado sandwich",
        name: 'Avocado sandwich',
        category: 'breakfast',
        price: '11$',
        amount: 0,
    },
    {
        id: 3,
        fav: "./images/Favorite.png",
        image: "images/WSwaffleB.png",
        alt: "Waffles",
        name: 'Waffles',
        category: 'breakfast',
        price: '12$',
        amount: 0,
    },
    {
        id: 4,
        fav: "./images/Favorite.png",
        image: "./images/eggSandB.png",
        alt: "Egg and meat",
        name: "Egg and meat",
        category: "breakfast",
        price: "12$",
        amount: 0,
    },
    {
        id: 5,
        fav: "./images/Favorite.png",
        image: "./images/KabsaL.png",
        alt: "Kabsa",
        name: "Kabsa",
        category: "lunch",
        price: "22$",
        amount: 0,
    },
    {
        id: 6,
        fav: "./images/Favorite.png",
        image: "./images/TheChiSL.png",
        alt: "Chicken with potato",
        name: "Chicken with potato",
        category: "lunch",
        price: "21$",
        amount: 0,
    },
    {
        id: 7,
        fav: "./images/Favorite.png",
        image: "./images/ChickenLegsL.png",
        alt: "Chicken legs",
        name: "Chicken wings",
        category: "lunch",
        price: "25$",
        amount: 0,
    },
    {
        id: 8,
        fav: "./images/Favorite.png",
        image: "./images/AvoBurE.png",
        alt: "Avocado with eggs",
        name: "Avocado with eggs",
        category: "evening",
        price: "18$",
        amount: 0,
    },
    {
        id: 9,
        fav: "./images/Favorite.png",
        image: "./images/PotatoE.png",
        alt: "Potatoes",
        name: "Potatoes",
        category: "evening",
        price: "16$",
        amount: 0,
    },
    {
        id: 10,
        fav: "./images/Favorite.png",
        image: "./images/SaladNE.png",
        alt: "Nuts salad",
        name: "Nuts salad",
        category: "evening",
        price: "14$",
        amount: 0,
    },
    {
        id: 11,
        fav: "./images/Favorite.png",
        image: "./images/SalamonD.png",
        alt: "Salmon salad",
        name: "Salmon salad",
        category: "dinner",
        price: "35$",
        amount: 0,
    },
    {
        id: 12,
        fav: "./images/Favorite.png",
        image: "./images/ShawarmaD.png",
        alt: "Shawarma",
        name: "Shawarma",
        category: "dinner",
        price: "10$",
        amount: 0,
    },
    {
        id: 13,
        fav: "./images/Favorite.png",
        image: "./images/RishSaladD.png",
        alt: "Rish salad",
        name: "Rish salad",
        category: "dinner",
        price: "40$",
        amount: 0,
    }
]

export default MenuD